### ISSUE TITLE
ModuleNotFoundError: No module named 'smplx'

### ISSUE THREAD

**Issue by monajalal** [facebookresearch/phosa#11]
Could you please guide how to fix this error? I followed all the steps before this command.
```
mona@mona:~/research/phosa$ python demo.py --filename input/000000038829.jpg
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    from phosa.bodymocap import get_bodymocap_predictor, process_mocap_predictions
  File "/home/mona/research/phosa/phosa/bodymocap.py", line 9, in <module>
    from bodymocap.body_mocap_api import BodyMocap
  File "./external/frankmocap/bodymocap/body_mocap_api.py", line 10, in <module>
    from bodymocap.models import hmr, SMPL, SMPLX
  File "./external/frankmocap/bodymocap/models/__init__.py", line 2, in <module>
    from .smpl import SMPL, SMPLX
  File "./external/frankmocap/bodymocap/models/smpl.py", line 6, in <module>
    import smplx
ModuleNotFoundError: No module named 'smplx'
```

Also,

```
mona@mona:~/research/phosa$ tree  extra_data/smpl/
extra_data/smpl/
├── basicModel_neutral_lbs_10_207_0_v1.0.0.pkl
├── dmpls
│   ├── female
│   │   └── model.npz
│   ├── LICENSE.txt
│   ├── male
│   │   └── model.npz
│   └── neutral
│       ├── model
│       │   └── eigvec.npy
│       └── model.npz
├── dmpls.tar.xz
├── mpips-smplify_public_v2
│   └── smplify_public
│       ├── code
│       │   ├── fit_3d.py
│       │   ├── lib
│       │   │   ├── capsule_body.py
│       │   │   ├── capsule_ch.py
│       │   │   ├── __init__.py
│       │   │   ├── max_mixture_prior.py
│       │   │   ├── robustifiers.py
│       │   │   └── sphere_collisions.py
│       │   ├── models
│       │   │   ├── basicModel_neutral_lbs_10_207_0_v1.0.0.pkl
│       │   │   ├── gmm_08.pkl
│       │   │   ├── regressors_locked_normalized_female.npz
│       │   │   ├── regressors_locked_normalized_hybrid.npz
│       │   │   └── regressors_locked_normalized_male.npz
│       │   ├── render_model.py
│       │   ├── show_humaneva.py
│       │   ├── visualize_mesh_sequence.m
│       │   └── visualize_mesh_sequence.py
│       ├── README.md
│       └── requirements.txt
├── mpips-smplify_public_v2.zip
├── SMPL_python_v.1.0.0
│   ├── __MACOSX
│   │   └── smpl
│   │       ├── models
│   │       └── smpl_webuser
│   │           └── hello_world
│   └── smpl
│       ├── __init__.py
│       ├── models
│       │   ├── basicModel_f_lbs_10_207_0_v1.0.0.pkl
│       │   └── basicmodel_m_lbs_10_207_0_v1.0.0.pkl
│       └── smpl_webuser
│           ├── hello_world
│           │   ├── hello_smpl.py
│           │   └── render_smpl.py
│           ├── __init__.py
│           ├── lbs.py
│           ├── LICENSE.txt
│           ├── posemapper.py
│           ├── README.txt
│           ├── serialization.py
│           └── verts.py
├── SMPL_python_v.1.0.0.zip
├── SMPL_python_v.1.1.0
│   └── smpl
│       ├── __init__.py
│       ├── models
│       │   ├── basicModel_f_lbs_10_207_0_v1.1.0.pkl
│       │   └── basicModel_m_lbs_10_207_0_v1.1.0.pkl
│       └── smpl_webuser
│           ├── hello_world
│           │   ├── hello_smpl.py
│           │   └── render_smpl.py
│           ├── __init__.py
│           ├── __init__.pyc
│           ├── lbs.py
│           ├── lbs.pyc
│           ├── LICENSE.txt
│           ├── posemapper.py
│           ├── posemapper.pyc
│           ├── README.txt
│           ├── serialization.py
│           ├── serialization.pyc
│           ├── verts.py
│           └── verts.pyc
└── SMPL_python_v.1.1.0.zip

25 directories, 57 files

```

**Comment by monajalal** [comment]
solved with https://github.com/facebookresearch/phosa/issues/12
