### ISSUE TITLE
AssertionError: Checkpoint detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl not found!

### ISSUE THREAD

**Issue by monajalal** [facebookresearch/phosa#17]
I had to install a fresh version on a new laptop (Ubuntu 20.04) and got this error. Could you please guide me how to fix it?

```
[185][mona.goku: phosa]$ python demo.py --filename input/000000038829.jpg
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

2020-12-19 00:23:29,591 INFO     Calling with args: Namespace(class_name='bicycle', filename='input/000000038829.jpg', lw_collision=None, lw_depth=None, lw_inter=None, lw_inter_part=None, lw_scale=None, lw_scale_person=None, lw_sil=None, mesh_index=0, output_dir='output')
2020-12-19 00:23:32,404 INFO     Loading checkpoint from detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
Traceback (most recent call last):
  File "demo.py", line 145, in <module>
    main(get_args())
  File "demo.py", line 105, in main
    segmenter = get_pointrend_predictor()
  File "/home/mona/research/phosa/phosa/pointrend.py", line 32, in get_pointrend_predictor
    return DefaultPredictor(cfg)
  File "/home/mona/anaconda3/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 188, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/home/mona/anaconda3/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 120, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl not found!

```

```
[186][mona.goku: phosa]$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.7.1'
```

**Comment by jasonyzhang** [comment]
Hi,

It looks like fvcore had some breaking changes. I've pinned fvcore to version 0.1.1.post20200716, and the colab notebook now works again. Let me know if you still have this problem after downgrading fvcore.

Best,
Jason

**Comment by monacv** [comment]
Hi Jason,

After your push, I still get the same error. Could you please have a look:
```

[8883:2271 0:370] 05:58:59 Wed Dec 23 [mona@goku:pts/1 +1] ~/research/code/phosa
$ python demo.py --filename input/000000038829.jpg
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 

2020-12-23 17:59:10,126 INFO     Calling with args: Namespace(class_name='bicycle', filename='input/000000038829.jpg', lw_collision=None, lw_depth=None, lw_inter=None, lw_inter_part=None, lw_scale=None, lw_scale_person=None, lw_sil=None, mesh_index=0, output_dir='output')
2020-12-23 17:59:13,445 INFO     Loading checkpoint from detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
Traceback (most recent call last):
  File "demo.py", line 145, in <module>
    main(get_args())
  File "demo.py", line 105, in main
    segmenter = get_pointrend_predictor()
  File "/home/mona/research/code/phosa/phosa/pointrend.py", line 32, in get_pointrend_predictor
    return DefaultPredictor(cfg)
  File "/home/mona/anaconda3/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 188, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/home/mona/anaconda3/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 120, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl not found!
19593/31773MB
[8883:2271 0:371] 05:59:13 Wed Dec 23 [mona@goku:pts/1 +1] ~/research/code/phosa
$ git log
commit d2aa89dd786bfe27925fcb96e4615706c0c6b2d6 (HEAD -> dev, origin/master, origin/HEAD, master)
Author: Jason Y. Zhang <jasonyzhang@cmu.edu>
Date:   Sun Dec 20 15:54:13 2020 -0800

    Pin fvcore version

commit 74d7c99a5a3d6804219445f0d22ca97f8ddf6989
Author: Jason Y. Zhang <jasonyzhang@cmu.edu>
Date:   Sun Dec 6 22:34:10 2020 -0800

    Update README.md


```

**Comment by jasonyzhang** [comment]
Could you try reinstalling the listed version of fvcore?

**Comment by monacv** [comment]
[FIXED] Thanks a lot :)
