### ISSUE TITLE
the demo.py code fails for certain jpg images?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#23]
When I run the code for two jpg images both of which have a bike, one of them produces the output files and the other one fails. Should the images follow specific criteria?
![bike_fix2](https://user-images.githubusercontent.com/76495162/112060694-e5354a80-8b33-11eb-92f9-0f1441dbdc06.jpg)

```
(phosa) mona@goku:~/research/code/phosa$ python demo.py --filename input/bike_fix2.jpg --class_name bicycle
2021-03-22 17:24:56,983 INFO     Calling with args: Namespace(class_name='bicycle', filename='input/bike_fix2.jpg', lw_collision=None, lw_depth=None, lw_inter=None, lw_inter_part=None, lw_scale=None, lw_scale_person=None, lw_sil=None, mesh_index=0, output_dir='output')
2021-03-22 17:25:00,213 INFO     Loading checkpoint from detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-22 17:25:00,213 INFO     URL https://dl.fbaipublicfiles.com/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl cached in /home/mona/.torch/iopath_cache/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-22 17:25:00,333 INFO     Reading a file from 'Detectron2 Model Zoo'
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Traceback (most recent call last):
  File "demo.py", line 145, in <module>
    main(get_args())
  File "demo.py", line 120, in main
    object_parameters = find_optimal_poses(
  File "/home/mona/research/code/phosa/phosa/pose_optimization.py", line 424, in find_optimal_poses
    object_parameters[k] = torch.stack(v)
RuntimeError: stack expects a non-empty TensorList
```

the one that passed:

![utility_bike1](https://user-images.githubusercontent.com/76495162/112060664-dc447900-8b33-11eb-8ba1-866e31536cd7.jpeg)

```
(phosa) mona@goku:~/research/code/phosa$ python demo.py --filename input/utility_bike1.jpeg --class_name bicycle
2021-03-22 16:56:35,397 INFO     Calling with args: Namespace(class_name='bicycle', filename='input/utility_bike1.jpeg', lw_collision=None, lw_depth=None, lw_inter=None, lw_inter_part=None, lw_scale=None, lw_scale_person=None, lw_sil=None, mesh_index=0, output_dir='output')
2021-03-22 16:56:40,401 INFO     Loading checkpoint from detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-22 16:56:40,401 INFO     URL https://dl.fbaipublicfiles.com/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl cached in /home/mona/.torch/iopath_cache/detectron2/PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
2021-03-22 16:56:40,508 INFO     Reading a file from 'Detectron2 Model Zoo'
WARNING: You are using a SMPL model, with only 10 shape coefficients.
loss: 5.59e+03: 100%|██████████████████████████████████████████████████████████████████████| 12500/12500.0 [10:25<00:00, 19.99it/s]
Loss 161.3118: 100%|█████████████████████████████████████████████████████████████████████████████| 400/400 [03:50<00:00,  1.74it/s]
2021-03-22 17:10:57,986 INFO     Saved rendered image to output/utility_bike1.jpeg.
2021-03-22 17:10:57,999 INFO     Saved top-down image to output/utility_bike1_top.jpeg.

```

**Comment by jasonyzhang** [comment]
It looks like the bicycle in the first picture was not detected by PointRend

**Comment by monacv** [comment]
when I ran the PointRed instance segmentation on the bike photo, it was able to detect it though. do you know what else could have gone wrong?

![Screenshot from 2021-03-22 18-51-56](https://user-images.githubusercontent.com/76495162/112068160-c046d480-8b3f-11eb-9b13-c6ba685dcc2d.png)

**Comment by jasonyzhang** [comment]
Actually, it looks like the the confidence score is 0.94, but I set the confidence threshold to 0.95. You can try lowering the threshold here:
https://github.com/facebookresearch/phosa/blob/d2aa89dd786bfe27925fcb96e4615706c0c6b2d6/phosa/pose_optimization.py#L380-L387

**Comment by monacv** [comment]
Thank you so much, it worked :) 
![Screenshot from 2021-03-22 20-44-14](https://user-images.githubusercontent.com/76495162/112075715-664e0b00-8b4f-11eb-817c-892fa7dca00f.png)
