### ISSUE TITLE
AssertionError: Checkpoint detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl not found!

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#28]
I had to setup phosa in another machine with 12G GPU. I got this error. I am not sure what I am missing. Could you please guide me?

```
(phosa) [jalal@goku phosa]$ python demo.py --filename input/easy_bat.jpg --class_name bat
2021-03-26 01:48:38,073 INFO     Calling with args: Namespace(class_name='bat', filename='input/easy_bat.jpg', lw_collision=None, lw_depth=None, lw_inter=None, lw_inter_part=None, lw_scale=None, lw_scale_person=None, lw_sil=None, mesh_index=0, output_dir='output')
2021-03-26 01:48:41,829 INFO     Loading checkpoint from detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl
Traceback (most recent call last):
  File "demo.py", line 145, in <module>
    main(get_args())
  File "demo.py", line 105, in main
    segmenter = get_pointrend_predictor()
  File "/scratch3/research/code/phosa/phosa/pointrend.py", line 32, in get_pointrend_predictor
    return DefaultPredictor(cfg)
  File "/scratch3/venv/phosa/lib64/python3.6/site-packages/detectron2/engine/defaults.py", line 188, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/scratch3/venv/phosa/lib64/python3.6/site-packages/fvcore/common/checkpoint.py", line 141, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/164955410/model_final_3c3198.pkl not found!

```

These are mentioned here:

```
POINTREND_MODEL_WEIGHTS = (
    "detectron2://PointRend/InstanceSegmentation/pointrend_rcnn_R_50_FPN_3x_coco/"
    "164955410/model_final_3c3198.pkl"
)

```

**Comment by monacv** [comment]
$ pip install fvcore==0.1.1.post20200716

**Comment by MohsenAziz** [comment]
i'm facing the same problem , seems like there is an issue with the pickle file , could you help?

**Comment by kunsuoh** [comment]
I have also same issue. I tried to install fvcore ==0.1.1.post20200716, but not working.
