### ISSUE TITLE
error in installing Detectron 2 following your instructions,       File "/tmp/pip-req-build-h5z6xwbr/setup.py", line 15, in <module>         assert torch_ver >= [1, 5], "Requires PyTorch >= 1.5"     AssertionError: Requires PyTorch >= 1.5

### ISSUE THREAD

**Issue by monajalal** [facebookresearch/phosa#5]
How should I fix this?
```
(phosa) mona@mona:~/research/phosa$ git clone https://github.com/facebookresearch/detectron2.git external/detectron2
Cloning into 'external/detectron2'...
remote: Enumerating objects: 9142, done.
remote: Total 9142 (delta 0), reused 0 (delta 0), pack-reused 9142
Receiving objects: 100% (9142/9142), 3.70 MiB | 26.88 MiB/s, done.
Resolving deltas: 100% (6689/6689), done.
(phosa) mona@mona:~/research/phosa$ pip install external/detectron2
Processing ./external/detectron2
    ERROR: Command errored out with exit status 1:
     command: /home/mona/anaconda3/envs/phosa/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-in3m0rdv/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-in3m0rdv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7p8dbz19
         cwd: /tmp/pip-req-build-in3m0rdv/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-in3m0rdv/setup.py", line 15, in <module>
        assert torch_ver >= [1, 5], "Requires PyTorch >= 1.5"
    AssertionError: Requires PyTorch >= 1.5
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

and

```
(phosa) mona@mona:~/research/phosa$ ls external/
total 16K
drwxrwxr-x  3 mona mona 4.0K Dec  6 16:06 ..
drwxrwxr-x  9 mona mona 4.0K Dec  6 16:07 multiperson
drwxrwxr-x  4 mona mona 4.0K Dec  6 16:08 .
drwxrwxr-x 15 mona mona 4.0K Dec  6 16:08 detectron2
(phosa) mona@mona:~/research/phosa$ ls external/detectron2/
total 164K
drwxrwxr-x  4 mona mona 4.0K Dec  6 16:08 ..
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:08 .circleci
-rw-rw-r--  1 mona mona 2.3K Dec  6 16:08 README.md
-rw-rw-r--  1 mona mona  48K Dec  6 16:08 MODEL_ZOO.md
-rw-rw-r--  1 mona mona  11K Dec  6 16:08 LICENSE
-rw-rw-r--  1 mona mona  12K Dec  6 16:08 INSTALL.md
-rw-rw-r--  1 mona mona  487 Dec  6 16:08 .gitignore
drwxrwxr-x  4 mona mona 4.0K Dec  6 16:08 .github
-rw-rw-r--  1 mona mona 3.3K Dec  6 16:08 GETTING_STARTED.md
-rw-rw-r--  1 mona mona  429 Dec  6 16:08 .flake8
drwxrwxr-x 13 mona mona 4.0K Dec  6 16:08 configs
-rw-rw-r--  1 mona mona 2.5K Dec  6 16:08 .clang-format
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:08 demo
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:08 datasets
drwxrwxr-x 15 mona mona 4.0K Dec  6 16:08 detectron2
drwxrwxr-x  6 mona mona 4.0K Dec  6 16:08 docs
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:08 docker
drwxrwxr-x  3 mona mona 4.0K Dec  6 16:08 dev
drwxrwxr-x  8 mona mona 4.0K Dec  6 16:08 projects
drwxrwxr-x  3 mona mona 4.0K Dec  6 16:08 tools
drwxrwxr-x  6 mona mona 4.0K Dec  6 16:08 tests
-rw-rw-r--  1 mona mona 7.7K Dec  6 16:08 setup.py
-rw-rw-r--  1 mona mona  846 Dec  6 16:08 setup.cfg
drwxrwxr-x  8 mona mona 4.0K Dec  6 16:08 .git
drwxrwxr-x 15 mona mona 4.0K Dec  6 16:08 .

```

also,

```
(phosa) mona@mona:~/research$ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

```
Also, I noticed you have the mkdir external 3 times. Is that a mistake? once should be enough.
![Screenshot_2020-12-06_16-12-14](https://user-images.githubusercontent.com/1892917/101292501-dec9cf80-37dd-11eb-9627-4968ae26f82b.png)

**Comment by monajalal** [comment]
```
$ git clone https://github.com/facebookresearch/phosa.git

(phosa) mona@mona:~/research$ cd phosa/
(phosa) mona@mona:~/research/phosa$ mkdir -p external
(phosa) mona@mona:~/research/phosa$ git clone https://github.com/JiangWenPL/multiperson.git external/multiperson
Cloning into 'external/multiperson'...
remote: Enumerating objects: 752, done.
remote: Counting objects: 100% (752/752), done.
remote: Compressing objects: 100% (566/566), done.
remote: Total 752 (delta 189), reused 723 (delta 173), pack-reused 0
Receiving objects: 100% (752/752), 48.29 MiB | 66.74 MiB/s, done.
Resolving deltas: 100% (189/189), done.
(phosa) mona@mona:~/research/phosa$ pip install external/multiperson/neural_renderer
Processing ./external/multiperson/neural_renderer
Building wheels for collected packages: neural-renderer-pytorch
  Building wheel for neural-renderer-pytorch (setup.py) ... done
  Created wheel for neural-renderer-pytorch: filename=neural_renderer_pytorch-1.1.3-cp37-cp37m-linux_x86_64.whl size=5993771 sha256=272cf6341a3b66173c9c460fccf7dea077b056c9d1c2a4fe3145f3ef6aa07068
  Stored in directory: /tmp/pip-ephem-wheel-cache-h26pygtd/wheels/c7/1b/84/10bf7a286a267887d8c7d382677c292cf18e1bba4e2508ed33
Successfully built neural-renderer-pytorch
Installing collected packages: neural-renderer-pytorch
  Attempting uninstall: neural-renderer-pytorch
    Found existing installation: neural-renderer-pytorch 1.1.3
    Uninstalling neural-renderer-pytorch-1.1.3:
      Successfully uninstalled neural-renderer-pytorch-1.1.3
Successfully installed neural-renderer-pytorch-1.1.3
(phosa) mona@mona:~/research/phosa$ git clone https://github.com/facebookresearch/detectron2.git external/detectron2
Cloning into 'external/detectron2'...
remote: Enumerating objects: 9142, done.
remote: Total 9142 (delta 0), reused 0 (delta 0), pack-reused 9142
Receiving objects: 100% (9142/9142), 3.70 MiB | 25.96 MiB/s, done.
Resolving deltas: 100% (6689/6689), done.
(phosa) mona@mona:~/research/phosa$ pip install external/detectron2
Processing ./external/detectron2
    ERROR: Command errored out with exit status 1:
     command: /home/mona/anaconda3/envs/phosa/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-h5z6xwbr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-h5z6xwbr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4eb8h3dv
         cwd: /tmp/pip-req-build-h5z6xwbr/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-h5z6xwbr/setup.py", line 15, in <module>
        assert torch_ver >= [1, 5], "Requires PyTorch >= 1.5"
    AssertionError: Requires PyTorch >= 1.5
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(phosa) mona@mona:~/research/phosa$ ls
total 88K
drwxrwxr-x 29 mona mona 4.0K Dec  6 16:15 ..
-rw-rw-r--  1 mona mona 3.8K Dec  6 16:15 README.md
-rw-rw-r--  1 mona mona  19K Dec  6 16:15 LICENSE.txt
-rw-rw-r--  1 mona mona  102 Dec  6 16:15 .gitignore
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:15 doc
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:15 dev
-rw-rw-r--  1 mona mona 5.0K Dec  6 16:15 demo.py
-rw-rw-r--  1 mona mona 1.3K Dec  6 16:15 CONTRIBUTING.md
-rw-rw-r--  1 mona mona 3.3K Dec  6 16:15 CODE_OF_CONDUCT.md
-rw-rw-r--  1 mona mona    0 Dec  6 16:15 test.txt
-rw-rw-r--  1 mona mona  641 Dec  6 16:15 setup.cfg
-rw-rw-r--  1 mona mona   85 Dec  6 16:15 requirements.txt
drwxrwxr-x  3 mona mona 4.0K Dec  6 16:15 phosa
drwxrwxr-x  3 mona mona 4.0K Dec  6 16:15 models
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:15 input
drwxrwxr-x  8 mona mona 4.0K Dec  6 16:15 .git
drwxrwxr-x  9 mona mona 4.0K Dec  6 16:15 .
drwxrwxr-x  4 mona mona 4.0K Dec  6 16:17 external
(phosa) mona@mona:~/research/phosa$ ls external
total 16K
drwxrwxr-x  9 mona mona 4.0K Dec  6 16:15 ..
drwxrwxr-x  9 mona mona 4.0K Dec  6 16:15 multiperson
drwxrwxr-x  4 mona mona 4.0K Dec  6 16:17 .
drwxrwxr-x 15 mona mona 4.0K Dec  6 16:17 detectron2
(phosa) mona@mona:~/research/phosa$ ls external/detectron2/
total 164K
drwxrwxr-x  4 mona mona 4.0K Dec  6 16:17 ..
-rw-rw-r--  1 mona mona  487 Dec  6 16:17 .gitignore
drwxrwxr-x  4 mona mona 4.0K Dec  6 16:17 .github
-rw-rw-r--  1 mona mona 3.3K Dec  6 16:17 GETTING_STARTED.md
-rw-rw-r--  1 mona mona  429 Dec  6 16:17 .flake8
-rw-rw-r--  1 mona mona 2.5K Dec  6 16:17 .clang-format
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:17 .circleci
-rw-rw-r--  1 mona mona 2.3K Dec  6 16:17 README.md
-rw-rw-r--  1 mona mona  48K Dec  6 16:17 MODEL_ZOO.md
-rw-rw-r--  1 mona mona  11K Dec  6 16:17 LICENSE
-rw-rw-r--  1 mona mona  12K Dec  6 16:17 INSTALL.md
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:17 demo
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:17 datasets
drwxrwxr-x 13 mona mona 4.0K Dec  6 16:17 configs
drwxrwxr-x  6 mona mona 4.0K Dec  6 16:17 docs
drwxrwxr-x  2 mona mona 4.0K Dec  6 16:17 docker
drwxrwxr-x  3 mona mona 4.0K Dec  6 16:17 dev
drwxrwxr-x 15 mona mona 4.0K Dec  6 16:17 detectron2
drwxrwxr-x  3 mona mona 4.0K Dec  6 16:17 tools
drwxrwxr-x  6 mona mona 4.0K Dec  6 16:17 tests
-rw-rw-r--  1 mona mona 7.7K Dec  6 16:17 setup.py
-rw-rw-r--  1 mona mona  846 Dec  6 16:17 setup.cfg
drwxrwxr-x  8 mona mona 4.0K Dec  6 16:17 projects
drwxrwxr-x  8 mona mona 4.0K Dec  6 16:17 .git
drwxrwxr-x 15 mona mona 4.0K Dec  6 16:17 .

```

**Comment by jasonyzhang** [comment]
Hi,

Looks like you've changed the assert flags in NMR to make it work for Pytorch 1.6 which is fine. I've updated the colab notebook so that it downloads detectron version 0.2.1 which still has support for Pytorch 1.4

`!git clone --branch v0.2.1 https://github.com/facebookresearch/detectron2.git external/detectron2`

**Comment by monajalal** [comment]
@jasonyzhang hi
I didn't change anything in the code and ran it following your instructions. It doesn't work with PyTorch 1.4


I tried it with PyTorch 1.6 and at least the Detectron2 and Neural Mesh Renderer are working now.

```
(base) mona@mona:~/research/phosa$ git clone https://github.com/facebookresearch/detectron2.git external/detectron2
Cloning into 'external/detectron2'...
remote: Enumerating objects: 9142, done.
remote: Total 9142 (delta 0), reused 0 (delta 0), pack-reused 9142
Receiving objects: 100% (9142/9142), 3.70 MiB | 28.50 MiB/s, done.
Resolving deltas: 100% (6693/6693), done.
(base) mona@mona:~/research/phosa$ pip install external/detectron2
Processing ./external/detectron2
Requirement already satisfied: termcolor>=1.1 in /home/mona/anaconda3/lib/python3.7/site-packages (from detectron2==0.3) (1.1.0)
Requirement already satisfied: Pillow>=7.1 in /home/mona/anaconda3/lib/python3.7/site-packages (from detectron2==0.3) (7.2.0)
Requirement already satisfied: yacs>=0.1.6 in /home/mona/anaconda3/lib/python3.7/site-packages (from detectron2==0.3) (0.1.7)
Requirement already satisfied: tabulate in /home/mona/anaconda3/lib/python3.7/site-packages (from detectron2==0.3) (0.8.7)
Requirement already satisfied: cloudpickle in /home/mona/anaconda3/lib/python3.7/site-packages (from detectron2==0.3) (1.6.0)
Requirement already satisfied: matplotlib in /home/mona/anaconda3/lib/python3.7/site-packages (from detectron2==0.3) (3.3.2)
Requirement already satisfied: tqdm>4.29.0 in /home/mona/anaconda3/lib/python3.7/site-packages (from detectron2==0.3) (4.49.0)
Requirement already satisfied: tensorboard in /home/mona/anaconda3/lib/python3.7/site-packages (from detectron2==0.3) (2.3.0)
Collecting fvcore>=0.1.2
  Downloading fvcore-0.1.2.post20201204.tar.gz (35 kB)
Collecting pycocotools>=2.0.2
  Downloading pycocotools-2.0.2.tar.gz (23 kB)
Requirement already satisfied: future in /home/mona/anaconda3/lib/python3.7/site-packages (from detectron2==0.3) (0.18.2)
Collecting pydot
  Downloading pydot-1.4.1-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: PyYAML in /home/mona/anaconda3/lib/python3.7/site-packages (from yacs>=0.1.6->detectron2==0.3) (5.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/mona/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.3) (2.4.7)
Requirement already satisfied: certifi>=2020.06.20 in /home/mona/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.3) (2020.6.20)
Requirement already satisfied: numpy>=1.15 in /home/mona/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.3) (1.18.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/mona/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.3) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/mona/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.3) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /home/mona/anaconda3/lib/python3.7/site-packages (from matplotlib->detectron2==0.3) (0.10.0)
Requirement already satisfied: requests<3,>=2.21.0 in /home/mona/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.3) (2.24.0)
Requirement already satisfied: six>=1.10.0 in /home/mona/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.3) (1.15.0)
Requirement already satisfied: markdown>=2.6.8 in /home/mona/anaconda3/lib/python3.7/site-packages/Markdown-3.2.2-py3.7.egg (from tensorboard->detectron2==0.3) (3.2.2)
Requirement already satisfied: werkzeug>=0.11.15 in /home/mona/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.3) (1.0.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/mona/anaconda3/lib/python3.7/site-packages/google_auth-1.17.2-py3.7.egg (from tensorboard->detectron2==0.3) (1.17.2)
Requirement already satisfied: protobuf>=3.6.0 in /home/mona/anaconda3/lib/python3.7/site-packages/protobuf-3.12.2-py3.7.egg (from tensorboard->detectron2==0.3) (3.12.2)
Requirement already satisfied: setuptools>=41.0.0 in /home/mona/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.3) (49.6.0.post20200917)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/mona/anaconda3/lib/python3.7/site-packages/tensorboard_plugin_wit-1.6.0.post3-py3.7.egg (from tensorboard->detectron2==0.3) (1.6.0.post3)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/mona/anaconda3/lib/python3.7/site-packages (from tensorboard->detectron2==0.3) (0.35.1)
Requirement already satisfied: absl-py>=0.4 in /home/mona/anaconda3/lib/python3.7/site-packages/absl_py-0.9.0-py3.7.egg (from tensorboard->detectron2==0.3) (0.9.0)
Requirement already satisfied: grpcio>=1.24.3 in /home/mona/anaconda3/lib/python3.7/site-packages/grpcio-1.30.0rc1-py3.7-linux-x86_64.egg (from tensorboard->detectron2==0.3) (1.30.0rc1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/mona/anaconda3/lib/python3.7/site-packages/google_auth_oauthlib-0.4.1-py3.7.egg (from tensorboard->detectron2==0.3) (0.4.1)
Requirement already satisfied: portalocker in /home/mona/anaconda3/lib/python3.7/site-packages (from fvcore>=0.1.2->detectron2==0.3) (1.7.0)
Requirement already satisfied: cython>=0.27.3 in /home/mona/anaconda3/lib/python3.7/site-packages (from pycocotools>=2.0.2->detectron2==0.3) (0.29.21)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/mona/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/mona/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/mona/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.3) (1.25.10)
Requirement already satisfied: importlib-metadata in /home/mona/anaconda3/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard->detectron2==0.3) (2.0.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/mona/anaconda3/lib/python3.7/site-packages/cachetools-4.1.0-py3.7.egg (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (4.1.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/mona/anaconda3/lib/python3.7/site-packages/pyasn1_modules-0.2.8-py3.7.egg (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/mona/anaconda3/lib/python3.7/site-packages/rsa-4.6-py3.7.egg (from google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (4.6)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/mona/anaconda3/lib/python3.7/site-packages/requests_oauthlib-1.3.0-py3.7.egg (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.3) (1.3.0)
Requirement already satisfied: zipp>=0.5 in /home/mona/anaconda3/lib/python3.7/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard->detectron2==0.3) (3.2.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/mona/anaconda3/lib/python3.7/site-packages/pyasn1-0.4.8-py3.7.egg (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard->detectron2==0.3) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /home/mona/anaconda3/lib/python3.7/site-packages/oauthlib-3.1.0-py3.7.egg (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.3) (3.1.0)
Building wheels for collected packages: detectron2, fvcore, pycocotools
  Building wheel for detectron2 (setup.py) ... done
  Created wheel for detectron2: filename=detectron2-0.3-cp37-cp37m-linux_x86_64.whl size=6235340 sha256=0e02b2276d6af95b4c73cb1eacd03d815c3d87ed256d4143243d137572566f7e
  Stored in directory: /tmp/pip-ephem-wheel-cache-27e63_am/wheels/e2/8b/34/dec28a66626853dcaf20ff80284fa70f0d34faa5f1f94efc82
  Building wheel for fvcore (setup.py) ... done
  Created wheel for fvcore: filename=fvcore-0.1.2.post20201204-py3-none-any.whl size=44621 sha256=b45a78c1ff371afed9899314c6fb8f18c1a2f2d7dd140a4a4c06a69dbd3c7f1d
  Stored in directory: /home/mona/.cache/pip/wheels/87/8f/3c/0cd35585b88b20c6849775b89a7e2c3f63a8ef240dd1bdd7a8
  Building wheel for pycocotools (setup.py) ... done
  Created wheel for pycocotools: filename=pycocotools-2.0.2-cp37-cp37m-linux_x86_64.whl size=369852 sha256=7435eb7676a74402ab1a2a3f91bedecb5ec67f12935fdb07f7b1b41b0743c84e
  Stored in directory: /home/mona/.cache/pip/wheels/bc/cf/1b/e95c99c5f9d1648be3f500ca55e7ce55f24818b0f48336adaf
Successfully built detectron2 fvcore pycocotools
Installing collected packages: fvcore, pycocotools, pydot, detectron2
  Attempting uninstall: fvcore
    Found existing installation: fvcore 0.1.1
    Uninstalling fvcore-0.1.1:
      Successfully uninstalled fvcore-0.1.1
  Attempting uninstall: pycocotools
    Found existing installation: pycocotools 2.0
    Uninstalling pycocotools-2.0:
      Successfully uninstalled pycocotools-2.0
  Attempting uninstall: detectron2
    Found existing installation: detectron2 0.1
    Uninstalling detectron2-0.1:
      Successfully uninstalled detectron2-0.1
Successfully installed detectron2-0.3 fvcore-0.1.2.post20201204 pycocotools-2.0.2 pydot-1.4.1

```
